### ISSUE TITLE
[Bug] Filter Keywords (blocked) not working when using Inoreader (Pluma 1.2.6 (2201050452) beta)

### ISSUE THREAD

**Issue by darrenmcentee** [qms-apps/Pluma-Android-Issue-Tracker#29]
There seems to be a bug in Filter Keywords when using Inoreader. Pluma 1.2.6 (2201050452) beta.
I have added many keywords and phrases to the Filter Keywords to be blocked.
But many articles that contain these keywords and phrases are still getting displayed.
I signed up for the pro sub for the exact feature.

**Comment by qijaz221** [comment]
[Needs Testing] Fixed in 1.2.8 beta.

**Comment by darrenmcentee** [comment]
While it seems to work mostly with my list of phrases, there are some that still get through. See attached one example. 
![Screenshot_20220119-074603](https://user-images.githubusercontent.com/2485782/150087209-b33681c3-95e3-4d4b-92d8-97505f2da831.png)
![Screenshot_20220119-074643](https://user-images.githubusercontent.com/2485782/150087216-2a294c41-7b0a-44da-a301-0102e19d3039.png)

Thank you,
Darren.

**Comment by darrenmcentee** [comment]
Just following up on this one. Confirming that a lot of blocked keywords are still getting allowed through.
